#!/usr/bin/env python3
"""Génère les screenshots Store pour les 25 langues (hors EN)."""

import asyncio, json
from pathlib import Path
from playwright.async_api import async_playwright

HTML = Path(__file__).parent / "screenshot-combined.html"
OUT  = Path(__file__).parent / "screenshots"
OUT.mkdir(exist_ok=True)

KBD = lambda t: f'<kbd style="background:rgba(255,255,255,0.3);border-radius:3px;padding:1px 5px;font-family:monospace;">Alt+S</kbd> {t}'

# ── Données par langue ────────────────────────────────────────────────────────
LANGS = {
"fr": {
    "step1": "Configurez vos snippets récurrents<br>directement dans l'extension",
    "step2": "Insérez instantanément vos snippets les plus courants dans n'importe quel champ texte — appuyez sur <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Éditeur",
    "importBtn": "⬆ Importer", "exportBtn": "⬇ Exporter",
    "shortcutLabel": "Raccourci clavier :", "configureLink": "· Configurer",
    "tabTree": "Arbre", "tabJson": "JSON brut",
    "hint": "Double-cliquez sur un nom ou une valeur pour l'éditer.",
    "treeMap": {"Company":"Société","VAT number":"Numéro de TVA","Company ID":"N° SIREN","Address":"Adresse","Booking links":"Liens visio","Brand colors":"Couleurs marque","Primary (mauve)":"Primaire (mauve)","Secondary (blue)":"Secondaire (bleu)","Emails":"Emails"},
    "col1b1": "Personnalisez le raccourci Alt+S",
    "col1b2": "Organisez en dossiers thématiques",
    "col1b3": "Éditez en ligne — double-cliquez sur la valeur",
    "formTitle": "Inscription fournisseur",
    "labelCompany": "Nom de la société", "labelVat": "Numéro de TVA", "labelMsg": "Message",
    "companyValue": "Acme France SAS",
    "textareaValue": "Bonjour,\nSi vous préférez, je peux vous retrouver sur Zoom.\nÀ bientôt, Alex",
    "bubble1": KBD("pour ouvrir les snippets"),
    "bubble2": "Naviguez, sélectionnez, insérez",
    "searchPlaceholder": "Recherche…",
    "panelFolderCompany": "Société", "panelSnipVat": "Numéro de TVA", "panelSnipId": "N° SIREN",
    "panelSnipAddr": "Adresse", "panelFolderBooking": "Liens visio", "panelFolderColors": "Couleurs marque",
},
"de": {
    "step1": "Richten Sie Ihre meistgenutzten Snippets<br>direkt in der Erweiterung ein",
    "step2": "Fügen Sie Snippets sofort in jedes Textfeld ein — drücken Sie <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Editor",
    "importBtn": "⬆ Importieren", "exportBtn": "⬇ Exportieren",
    "shortcutLabel": "Tastenkürzel:", "configureLink": "· Anpassen",
    "tabTree": "Baum", "tabJson": "JSON",
    "hint": "Doppelklick auf Name oder Wert zum Bearbeiten.",
    "treeMap": {"Company":"Unternehmen","VAT number":"USt-IdNr.","Company ID":"Firmen-ID","Address":"Adresse","Booking links":"Meeting-Links","Brand colors":"Markenfarben","Primary (mauve)":"Primär (mauve)","Secondary (blue)":"Sekundär (blau)","Emails":"E-Mails"},
    "col1b1": "Alt+S-Kürzel anpassen",
    "col1b2": "In Ordnern organisieren",
    "col1b3": "Inline bearbeiten — doppelklicken",
    "formTitle": "Lieferantenregistrierung",
    "labelCompany": "Unternehmen", "labelVat": "USt-IdNr.", "labelMsg": "Nachricht",
    "companyValue": "Acme GmbH",
    "textareaValue": "Hallo,\nBei Bedarf können wir uns auch per Zoom treffen.\nBis bald, Alex",
    "bubble1": KBD("zum Öffnen"),
    "bubble2": "Durchsuchen, auswählen, einfügen",
    "searchPlaceholder": "Suchen…",
    "panelFolderCompany": "Unternehmen", "panelSnipVat": "USt-IdNr.", "panelSnipId": "Firmen-ID",
    "panelSnipAddr": "Adresse", "panelFolderBooking": "Meeting-Links", "panelFolderColors": "Markenfarben",
},
"es": {
    "step1": "Configura tus snippets más usados<br>directamente en la extensión",
    "step2": "Inserta al instante tus snippets en cualquier campo de texto — pulsa <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Editor",
    "importBtn": "⬆ Importar", "exportBtn": "⬇ Exportar",
    "shortcutLabel": "Atajo de teclado:", "configureLink": "· Configurar",
    "tabTree": "Árbol", "tabJson": "JSON",
    "hint": "Doble clic en un nombre o valor para editarlo.",
    "treeMap": {"Company":"Empresa","VAT number":"NIF/CIF","Company ID":"ID empresa","Address":"Dirección","Booking links":"Videollamadas","Brand colors":"Colores marca","Primary (mauve)":"Principal (malva)","Secondary (blue)":"Secundario (azul)","Emails":"Correos"},
    "col1b1": "Personaliza el atajo Alt+S",
    "col1b2": "Organiza en carpetas",
    "col1b3": "Edita en línea — doble clic en el valor",
    "formTitle": "Registro de proveedor",
    "labelCompany": "Empresa", "labelVat": "NIF/CIF", "labelMsg": "Mensaje",
    "companyValue": "Acme España S.L.",
    "textareaValue": "Hola,\nSi lo prefiere, podemos vernos por Zoom.\nHasta pronto, Alex",
    "bubble1": KBD("para abrir"),
    "bubble2": "Navega, selecciona, inserta",
    "searchPlaceholder": "Buscar…",
    "panelFolderCompany": "Empresa", "panelSnipVat": "NIF/CIF", "panelSnipId": "ID empresa",
    "panelSnipAddr": "Dirección", "panelFolderBooking": "Videollamadas", "panelFolderColors": "Colores marca",
},
"it": {
    "step1": "Configura i tuoi snippet più usati<br>direttamente nell'estensione",
    "step2": "Inserisci istantaneamente i snippet in qualsiasi campo — premi <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Editor",
    "importBtn": "⬆ Importa", "exportBtn": "⬇ Esporta",
    "shortcutLabel": "Scorciatoia:", "configureLink": "· Configura",
    "tabTree": "Albero", "tabJson": "JSON",
    "hint": "Doppio clic su nome o valore per modificarlo.",
    "treeMap": {"Company":"Azienda","VAT number":"Partita IVA","Company ID":"Codice fiscale","Address":"Indirizzo","Booking links":"Link riunioni","Brand colors":"Colori brand","Primary (mauve)":"Primario (malva)","Secondary (blue)":"Secondario (blu)","Emails":"Email"},
    "col1b1": "Personalizza il tasto Alt+S",
    "col1b2": "Organizza in cartelle",
    "col1b3": "Modifica in linea — doppio clic",
    "formTitle": "Registrazione fornitore",
    "labelCompany": "Azienda", "labelVat": "Partita IVA", "labelMsg": "Messaggio",
    "companyValue": "Acme Italia S.r.l.",
    "textareaValue": "Salve,\nSe preferisce, possiamo incontrarci su Zoom.\nA presto, Alex",
    "bubble1": KBD("per aprire"),
    "bubble2": "Sfoglia, seleziona, inserisci",
    "searchPlaceholder": "Cerca…",
    "panelFolderCompany": "Azienda", "panelSnipVat": "P. IVA", "panelSnipId": "Cod. fiscale",
    "panelSnipAddr": "Indirizzo", "panelFolderBooking": "Link riunioni", "panelFolderColors": "Colori brand",
},
"pt": {
    "step1": "Configure os seus snippets mais usados<br>diretamente na extensão",
    "step2": "Insira instantaneamente snippets em qualquer campo de texto — prima <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Editor",
    "importBtn": "⬆ Importar", "exportBtn": "⬇ Exportar",
    "shortcutLabel": "Atalho de teclado:", "configureLink": "· Configurar",
    "tabTree": "Árvore", "tabJson": "JSON",
    "hint": "Duplo clique num nome ou valor para editar.",
    "treeMap": {"Company":"Empresa","VAT number":"NIF","Company ID":"ID empresa","Address":"Morada","Booking links":"Links reunião","Brand colors":"Cores da marca","Primary (mauve)":"Principal (malva)","Secondary (blue)":"Secundário (azul)","Emails":"Emails"},
    "col1b1": "Personalize o atalho Alt+S",
    "col1b2": "Organize em pastas",
    "col1b3": "Edite inline — duplo clique no valor",
    "formTitle": "Registo de fornecedor",
    "labelCompany": "Empresa", "labelVat": "NIF", "labelMsg": "Mensagem",
    "companyValue": "Acme Portugal Lda.",
    "textareaValue": "Olá,\nSe preferir, podemos reunir via Zoom.\nAté breve, Alex",
    "bubble1": KBD("para abrir"),
    "bubble2": "Navegue, selecione, insira",
    "searchPlaceholder": "Pesquisar…",
    "panelFolderCompany": "Empresa", "panelSnipVat": "NIF", "panelSnipId": "ID empresa",
    "panelSnipAddr": "Morada", "panelFolderBooking": "Links reunião", "panelFolderColors": "Cores da marca",
},
"nl": {
    "step1": "Stel je meest gebruikte snippets in<br>direct in de extensie",
    "step2": "Plak snippets direct in elk tekstveld — druk op <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Editor",
    "importBtn": "⬆ Importeren", "exportBtn": "⬇ Exporteren",
    "shortcutLabel": "Sneltoets:", "configureLink": "· Aanpassen",
    "tabTree": "Structuur", "tabJson": "JSON",
    "hint": "Dubbelklik op een naam of waarde om te bewerken.",
    "treeMap": {"Company":"Bedrijf","VAT number":"BTW-nummer","Company ID":"KvK-nummer","Address":"Adres","Booking links":"Vergaderlinks","Brand colors":"Merkkleuren","Primary (mauve)":"Primair (mauve)","Secondary (blue)":"Secundair (blauw)","Emails":"E-mails"},
    "col1b1": "Pas Alt+S-sneltoets aan",
    "col1b2": "Organiseer in mappen",
    "col1b3": "Bewerk inline — dubbelklik",
    "formTitle": "Leveranciersregistratie",
    "labelCompany": "Bedrijf", "labelVat": "BTW-nummer", "labelMsg": "Bericht",
    "companyValue": "Acme Nederland B.V.",
    "textareaValue": "Hallo,\nAls u wilt, kunnen we ook via Zoom vergaderen.\nTot snel, Alex",
    "bubble1": KBD("om te openen"),
    "bubble2": "Blader, selecteer, plak",
    "searchPlaceholder": "Zoeken…",
    "panelFolderCompany": "Bedrijf", "panelSnipVat": "BTW-nr.", "panelSnipId": "KvK-nr.",
    "panelSnipAddr": "Adres", "panelFolderBooking": "Vergaderlinks", "panelFolderColors": "Merkkleuren",
},
"pl": {
    "step1": "Skonfiguruj najczęściej używane snippety<br>bezpośrednio w rozszerzeniu",
    "step2": "Wstawiaj snippety błyskawicznie w każde pole — naciśnij <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Edytor",
    "importBtn": "⬆ Importuj", "exportBtn": "⬇ Eksportuj",
    "shortcutLabel": "Skrót klawiszowy:", "configureLink": "· Skonfiguruj",
    "tabTree": "Drzewo", "tabJson": "JSON",
    "hint": "Dwuklik na nazwę lub wartość, aby edytować.",
    "treeMap": {"Company":"Firma","VAT number":"NIP","Company ID":"REGON","Address":"Adres","Booking links":"Linki spotkań","Brand colors":"Kolory marki","Primary (mauve)":"Główny (mauve)","Secondary (blue)":"Drugorzędny (niebieski)","Emails":"E-maile"},
    "col1b1": "Dostosuj skrót Alt+S",
    "col1b2": "Organizuj w folderach",
    "col1b3": "Edytuj w miejscu — dwuklik",
    "formTitle": "Rejestracja dostawcy",
    "labelCompany": "Firma", "labelVat": "NIP", "labelMsg": "Wiadomość",
    "companyValue": "Acme Polska Sp. z o.o.",
    "textareaValue": "Dzień dobry,\nJeśli wolą Państwo, możemy spotkać się przez Zoom.\nDo zobaczenia, Alex",
    "bubble1": KBD("aby otworzyć"),
    "bubble2": "Przeglądaj, wybierz, wstaw",
    "searchPlaceholder": "Szukaj…",
    "panelFolderCompany": "Firma", "panelSnipVat": "NIP", "panelSnipId": "REGON",
    "panelSnipAddr": "Adres", "panelFolderBooking": "Linki spotkań", "panelFolderColors": "Kolory marki",
},
"sv": {
    "step1": "Konfigurera dina mest använda snippets<br>direkt i tillägget",
    "step2": "Infoga snippets direkt i valfritt textfält — tryck på <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Redigerare",
    "importBtn": "⬆ Importera", "exportBtn": "⬇ Exportera",
    "shortcutLabel": "Tangentbordsgenväg:", "configureLink": "· Anpassa",
    "tabTree": "Träd", "tabJson": "JSON",
    "hint": "Dubbelklicka på ett namn eller värde för att redigera.",
    "treeMap": {"Company":"Företag","VAT number":"Org.nr.","Company ID":"Momsreg.nr.","Address":"Adress","Booking links":"Möteslänkar","Brand colors":"Varumärkesfärger","Primary (mauve)":"Primär (mauve)","Secondary (blue)":"Sekundär (blå)","Emails":"E-post"},
    "col1b1": "Anpassa Alt+S-genvägen",
    "col1b2": "Organisera i mappar",
    "col1b3": "Redigera direkt — dubbelklicka",
    "formTitle": "Leverantörsregistrering",
    "labelCompany": "Företag", "labelVat": "Momsreg.nr.", "labelMsg": "Meddelande",
    "companyValue": "Acme Sverige AB",
    "textareaValue": "Hej,\nOm du föredrar det kan vi ses via Zoom.\nHälsningar, Alex",
    "bubble1": KBD("för att öppna"),
    "bubble2": "Bläddra, välj, infoga",
    "searchPlaceholder": "Sök…",
    "panelFolderCompany": "Företag", "panelSnipVat": "Momsreg.nr.", "panelSnipId": "Org.nr.",
    "panelSnipAddr": "Adress", "panelFolderBooking": "Möteslänkar", "panelFolderColors": "Varumärkesfärger",
},
"da": {
    "step1": "Konfigurer dine mest brugte snippets<br>direkte i udvidelsen",
    "step2": "Indsæt snippets øjeblikkeligt i ethvert tekstfelt — tryk <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Redaktør",
    "importBtn": "⬆ Importer", "exportBtn": "⬇ Eksporter",
    "shortcutLabel": "Tastaturgenvej:", "configureLink": "· Konfigurer",
    "tabTree": "Træ", "tabJson": "JSON",
    "hint": "Dobbeltklik på et navn eller en værdi for at redigere.",
    "treeMap": {"Company":"Virksomhed","VAT number":"CVR-nummer","Company ID":"Firma-ID","Address":"Adresse","Booking links":"Mødelinks","Brand colors":"Brandfarver","Primary (mauve)":"Primær (mauve)","Secondary (blue)":"Sekundær (blå)","Emails":"E-mails"},
    "col1b1": "Tilpas Alt+S-genvejen",
    "col1b2": "Organiser i mapper",
    "col1b3": "Rediger direkte — dobbeltklik",
    "formTitle": "Leverandørregistrering",
    "labelCompany": "Virksomhed", "labelVat": "CVR-nummer", "labelMsg": "Besked",
    "companyValue": "Acme Danmark ApS",
    "textareaValue": "Hej,\nHvis du foretrækker det, kan vi mødes via Zoom.\nMed venlig hilsen, Alex",
    "bubble1": KBD("for at åbne"),
    "bubble2": "Gennemse, vælg, indsæt",
    "searchPlaceholder": "Søg…",
    "panelFolderCompany": "Virksomhed", "panelSnipVat": "CVR-nr.", "panelSnipId": "Firma-ID",
    "panelSnipAddr": "Adresse", "panelFolderBooking": "Mødelinks", "panelFolderColors": "Brandfarver",
},
"nb": {
    "step1": "Konfigurer de mest brukte snippetene<br>direkte i utvidelsen",
    "step2": "Lim inn snippets umiddelbart i alle tekstfelt — trykk <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Redaktør",
    "importBtn": "⬆ Importer", "exportBtn": "⬇ Eksporter",
    "shortcutLabel": "Tastatursnarveig:", "configureLink": "· Konfigurer",
    "tabTree": "Tre", "tabJson": "JSON",
    "hint": "Dobbeltklikk på et navn eller en verdi for å redigere.",
    "treeMap": {"Company":"Bedrift","VAT number":"Org.nr.","Company ID":"Bedrifts-ID","Address":"Adresse","Booking links":"Møtelenker","Brand colors":"Merkefarger","Primary (mauve)":"Primær (mauve)","Secondary (blue)":"Sekundær (blå)","Emails":"E-poster"},
    "col1b1": "Tilpass Alt+S-snarveien",
    "col1b2": "Organiser i mapper",
    "col1b3": "Rediger direkte — dobbeltklikk",
    "formTitle": "Leverandørregistrering",
    "labelCompany": "Bedrift", "labelVat": "Org.nr.", "labelMsg": "Melding",
    "companyValue": "Acme Norge AS",
    "textareaValue": "Hei,\nHvis du foretrekker det, kan vi møtes på Zoom.\nMed vennlig hilsen, Alex",
    "bubble1": KBD("for å åpne"),
    "bubble2": "Bla, velg, sett inn",
    "searchPlaceholder": "Søk…",
    "panelFolderCompany": "Bedrift", "panelSnipVat": "Org.nr.", "panelSnipId": "Bedrifts-ID",
    "panelSnipAddr": "Adresse", "panelFolderBooking": "Møtelenker", "panelFolderColors": "Merkefarger",
},
"fi": {
    "step1": "Määritä käytetyimmät snippetisi<br>suoraan laajennuksessa",
    "step2": "Liitä snippetit välittömästi mihin tahansa tekstikenttään — paina <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Muokkain",
    "importBtn": "⬆ Tuo", "exportBtn": "⬇ Vie",
    "shortcutLabel": "Pikanäppäin:", "configureLink": "· Mukauta",
    "tabTree": "Puu", "tabJson": "JSON",
    "hint": "Kaksoisnapsauta nimeä tai arvoa muokataksesi.",
    "treeMap": {"Company":"Yritys","VAT number":"ALV-numero","Company ID":"Y-tunnus","Address":"Osoite","Booking links":"Kokouslinkit","Brand colors":"Brändivärit","Primary (mauve)":"Ensisijainen (mauve)","Secondary (blue)":"Toissijainen (sininen)","Emails":"Sähköpostit"},
    "col1b1": "Mukauta Alt+S-pikakuvake",
    "col1b2": "Järjestä kansioihin",
    "col1b3": "Muokkaa suoraan — kaksoisnapsauta",
    "formTitle": "Toimittajan rekisteröinti",
    "labelCompany": "Yritys", "labelVat": "ALV-numero", "labelMsg": "Viesti",
    "companyValue": "Acme Suomi Oy",
    "textareaValue": "Hei,\nVoidaan myös tavata Zoomin kautta.\nNähdään pian, Alex",
    "bubble1": KBD("avataksesi"),
    "bubble2": "Selaa, valitse, lisää",
    "searchPlaceholder": "Hae…",
    "panelFolderCompany": "Yritys", "panelSnipVat": "ALV-nro", "panelSnipId": "Y-tunnus",
    "panelSnipAddr": "Osoite", "panelFolderBooking": "Kokouslinkit", "panelFolderColors": "Brändivärit",
},
"cs": {
    "step1": "Nakonfigurujte nejpoužívanější snippety<br>přímo v rozšíření",
    "step2": "Vkládejte snippety okamžitě do libovolného pole — stiskněte <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Editor",
    "importBtn": "⬆ Importovat", "exportBtn": "⬇ Exportovat",
    "shortcutLabel": "Klávesová zkratka:", "configureLink": "· Nastavit",
    "tabTree": "Strom", "tabJson": "JSON",
    "hint": "Dvojklikem na název nebo hodnotu jej upravte.",
    "treeMap": {"Company":"Společnost","VAT number":"DIČ","Company ID":"IČO","Address":"Adresa","Booking links":"Schůzkové odkazy","Brand colors":"Barvy značky","Primary (mauve)":"Primární (mauve)","Secondary (blue)":"Sekundární (modrá)","Emails":"E-maily"},
    "col1b1": "Přizpůsobte zkratku Alt+S",
    "col1b2": "Uspořádejte do složek",
    "col1b3": "Upravujte přímo — poklepejte",
    "formTitle": "Registrace dodavatele",
    "labelCompany": "Společnost", "labelVat": "DIČ", "labelMsg": "Zpráva",
    "companyValue": "Acme Česko s.r.o.",
    "textareaValue": "Dobrý den,\nMůžeme se také setkat přes Zoom.\nS pozdravem, Alex",
    "bubble1": KBD("pro otevření"),
    "bubble2": "Procházejte, vyberte, vložte",
    "searchPlaceholder": "Hledat…",
    "panelFolderCompany": "Společnost", "panelSnipVat": "DIČ", "panelSnipId": "IČO",
    "panelSnipAddr": "Adresa", "panelFolderBooking": "Schůzky", "panelFolderColors": "Barvy značky",
},
"sk": {
    "step1": "Nakonfigurujte najpoužívanejšie snippety<br>priamo v rozšírení",
    "step2": "Vkladajte snippety okamžite do akéhokoľvek poľa — stlačte <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Editor",
    "importBtn": "⬆ Importovať", "exportBtn": "⬇ Exportovať",
    "shortcutLabel": "Klávesová skratka:", "configureLink": "· Nastaviť",
    "tabTree": "Strom", "tabJson": "JSON",
    "hint": "Dvojklikom na názov alebo hodnotu ho upravte.",
    "treeMap": {"Company":"Spoločnosť","VAT number":"IČ DPH","Company ID":"IČO","Address":"Adresa","Booking links":"Linky na stretnutia","Brand colors":"Farby značky","Primary (mauve)":"Primárna (mauve)","Secondary (blue)":"Sekundárna (modrá)","Emails":"E-maily"},
    "col1b1": "Prispôsobte skratku Alt+S",
    "col1b2": "Usporiadajte do priečinkov",
    "col1b3": "Upravte priamo — dvojklik",
    "formTitle": "Registrácia dodávateľa",
    "labelCompany": "Spoločnosť", "labelVat": "IČ DPH", "labelMsg": "Správa",
    "companyValue": "Acme Slovensko s.r.o.",
    "textareaValue": "Dobrý deň,\nMôžeme sa tiež stretnúť cez Zoom.\nS pozdravom, Alex",
    "bubble1": KBD("na otvorenie"),
    "bubble2": "Prechádzajte, vyberte, vložte",
    "searchPlaceholder": "Hľadať…",
    "panelFolderCompany": "Spoločnosť", "panelSnipVat": "IČ DPH", "panelSnipId": "IČO",
    "panelSnipAddr": "Adresa", "panelFolderBooking": "Stretnutia", "panelFolderColors": "Farby značky",
},
"hu": {
    "step1": "Állítsa be a leggyakrabban használt<br>snippetjeit az bővítményben",
    "step2": "Illessze be a snippeteket azonnal bármely szövegmezőbe — nyomja meg az <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Szerkesztő",
    "importBtn": "⬆ Importálás", "exportBtn": "⬇ Exportálás",
    "shortcutLabel": "Billentyűparancs:", "configureLink": "· Beállítás",
    "tabTree": "Fa", "tabJson": "JSON",
    "hint": "Kattintson duplán a névre vagy értékre a szerkesztéshez.",
    "treeMap": {"Company":"Cég","VAT number":"Adószám","Company ID":"Cégjegyzékszám","Address":"Cím","Booking links":"Megbeszélési linkek","Brand colors":"Márkafarben","Primary (mauve)":"Elsődleges (mauve)","Secondary (blue)":"Másodlagos (kék)","Emails":"E-mailek"},
    "col1b1": "Testreszabja az Alt+S billentyűt",
    "col1b2": "Rendezze mappákba",
    "col1b3": "Szerkessze helyben — dupla kattintás",
    "formTitle": "Szállító regisztrációja",
    "labelCompany": "Cég", "labelVat": "Adószám", "labelMsg": "Üzenet",
    "companyValue": "Acme Magyarország Kft.",
    "textareaValue": "Tisztelt Alex,\nSzívesen találkozhatunk Zoom-on is.\nÜdvözlettel, Alex",
    "bubble1": KBD("megnyitáshoz"),
    "bubble2": "Böngésszen, válasszon, illesszen be",
    "searchPlaceholder": "Keresés…",
    "panelFolderCompany": "Cég", "panelSnipVat": "Adószám", "panelSnipId": "Cégjegyz.sz.",
    "panelSnipAddr": "Cím", "panelFolderBooking": "Megbeszélések", "panelFolderColors": "Márkafarben",
},
"ro": {
    "step1": "Configurați cele mai utilizate snippeturi<br>direct în extensie",
    "step2": "Inserați instant snippeturi în orice câmp text — apăsați <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Editor",
    "importBtn": "⬆ Importați", "exportBtn": "⬇ Exportați",
    "shortcutLabel": "Comandă rapidă:", "configureLink": "· Configurați",
    "tabTree": "Arbore", "tabJson": "JSON",
    "hint": "Dublu clic pe un nume sau valoare pentru a edita.",
    "treeMap": {"Company":"Companie","VAT number":"CUI/TVA","Company ID":"Nr. Reg. Com.","Address":"Adresă","Booking links":"Linkuri întâlniri","Brand colors":"Culori brand","Primary (mauve)":"Primar (mauve)","Secondary (blue)":"Secundar (albastru)","Emails":"E-mailuri"},
    "col1b1": "Personalizați scurtătura Alt+S",
    "col1b2": "Organizați în dosare",
    "col1b3": "Editați direct — dublu clic",
    "formTitle": "Înregistrare furnizor",
    "labelCompany": "Companie", "labelVat": "CUI/TVA", "labelMsg": "Mesaj",
    "companyValue": "Acme România S.R.L.",
    "textareaValue": "Bună ziua,\nPutem discuta și pe Zoom dacă preferați.\nCu stimă, Alex",
    "bubble1": KBD("pentru deschidere"),
    "bubble2": "Navigați, selectați, inserați",
    "searchPlaceholder": "Căutare…",
    "panelFolderCompany": "Companie", "panelSnipVat": "CUI/TVA", "panelSnipId": "Nr. Reg.",
    "panelSnipAddr": "Adresă", "panelFolderBooking": "Întâlniri", "panelFolderColors": "Culori brand",
},
"hr": {
    "step1": "Konfigurirajte najkorištenije snippete<br>izravno u proširenju",
    "step2": "Odmah umetnite snippete u bilo koje polje — pritisnite <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Urednik",
    "importBtn": "⬆ Uvezi", "exportBtn": "⬇ Izvezi",
    "shortcutLabel": "Tipkovni prečac:", "configureLink": "· Konfiguriraj",
    "tabTree": "Stablo", "tabJson": "JSON",
    "hint": "Dvostruki klik na ime ili vrijednost za uređivanje.",
    "treeMap": {"Company":"Tvrtka","VAT number":"OIB / PDV","Company ID":"MB","Address":"Adresa","Booking links":"Linkovi za sastanke","Brand colors":"Boje branda","Primary (mauve)":"Primarna (mauve)","Secondary (blue)":"Sekundarna (plava)","Emails":"E-pošta"},
    "col1b1": "Prilagodite prečac Alt+S",
    "col1b2": "Organizirajte u mape",
    "col1b3": "Uredite izravno — dvostruki klik",
    "formTitle": "Registracija dobavljača",
    "labelCompany": "Tvrtka", "labelVat": "OIB/PDV", "labelMsg": "Poruka",
    "companyValue": "Acme Hrvatska d.o.o.",
    "textareaValue": "Poštovani,\nMožemo se i sastati putem Zooma.\nSrdačan pozdrav, Alex",
    "bubble1": KBD("za otvaranje"),
    "bubble2": "Pregledajte, odaberite, umetnite",
    "searchPlaceholder": "Pretraži…",
    "panelFolderCompany": "Tvrtka", "panelSnipVat": "OIB/PDV", "panelSnipId": "MB",
    "panelSnipAddr": "Adresa", "panelFolderBooking": "Sastanci", "panelFolderColors": "Boje branda",
},
"bg": {
    "step1": "Настройте най-използваните фрагменти<br>директно в разширението",
    "step2": "Вмъквайте фрагменти мигновено в произволно поле — натиснете <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Редактор",
    "importBtn": "⬆ Импорт", "exportBtn": "⬇ Експорт",
    "shortcutLabel": "Клавишна комбинация:", "configureLink": "· Конфигурирайте",
    "tabTree": "Дърво", "tabJson": "JSON",
    "hint": "Двоен клик върху име или стойност за редактиране.",
    "treeMap": {"Company":"Фирма","VAT number":"ДДС номер","Company ID":"ЕИК","Address":"Адрес","Booking links":"Линкове за срещи","Brand colors":"Фирмени цветове","Primary (mauve)":"Основен (mauve)","Secondary (blue)":"Допълнителен (синьо)","Emails":"Имейли"},
    "col1b1": "Персонализирайте Alt+S",
    "col1b2": "Организирайте в папки",
    "col1b3": "Редактирайте — двоен клик",
    "formTitle": "Регистрация на доставчик",
    "labelCompany": "Фирма", "labelVat": "ДДС номер", "labelMsg": "Съобщение",
    "companyValue": "Акме България ЕООД",
    "textareaValue": "Здравейте,\nМожем да се срещнем и в Zoom.\nПоздрави, Алекс",
    "bubble1": KBD("за отваряне"),
    "bubble2": "Прелистете, изберете, вмъкнете",
    "searchPlaceholder": "Търсене…",
    "panelFolderCompany": "Фирма", "panelSnipVat": "ДДС номер", "panelSnipId": "ЕИК",
    "panelSnipAddr": "Адрес", "panelFolderBooking": "Срещи", "panelFolderColors": "Цветове",
},
"el": {
    "step1": "Ρυθμίστε τα πιο χρησιμοποιημένα snippets<br>απευθείας στην επέκταση",
    "step2": "Εισαγάγετε snippets άμεσα σε οποιοδήποτε πεδίο — πατήστε <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Επεξεργαστής",
    "importBtn": "⬆ Εισαγωγή", "exportBtn": "⬇ Εξαγωγή",
    "shortcutLabel": "Συντόμευση:", "configureLink": "· Ρύθμιση",
    "tabTree": "Δέντρο", "tabJson": "JSON",
    "hint": "Διπλό κλικ σε όνομα ή τιμή για επεξεργασία.",
    "treeMap": {"Company":"Εταιρεία","VAT number":"ΑΦΜ","Company ID":"ΓΕΜΗ","Address":"Διεύθυνση","Booking links":"Σύνδεσμοι συναντήσεων","Brand colors":"Εταιρικά χρώματα","Primary (mauve)":"Κύριο (mauve)","Secondary (blue)":"Δευτερεύον (μπλε)","Emails":"Email"},
    "col1b1": "Προσαρμόστε το Alt+S",
    "col1b2": "Οργανώστε σε φακέλους",
    "col1b3": "Επεξεργαστείτε — διπλό κλικ",
    "formTitle": "Εγγραφή προμηθευτή",
    "labelCompany": "Εταιρεία", "labelVat": "ΑΦΜ", "labelMsg": "Μήνυμα",
    "companyValue": "Acme Ελλάδα ΕΠΕ",
    "textareaValue": "Γεια σας,\nΜπορούμε να συναντηθούμε και μέσω Zoom.\nΦιλικά, Αλεξ",
    "bubble1": KBD("για άνοιγμα"),
    "bubble2": "Περιηγηθείτε, επιλέξτε, εισαγάγετε",
    "searchPlaceholder": "Αναζήτηση…",
    "panelFolderCompany": "Εταιρεία", "panelSnipVat": "ΑΦΜ", "panelSnipId": "ΓΕΜΗ",
    "panelSnipAddr": "Διεύθυνση", "panelFolderBooking": "Συναντήσεις", "panelFolderColors": "Χρώματα",
},
"tr": {
    "step1": "En çok kullandığınız snippet'leri<br>doğrudan uzantıda yapılandırın",
    "step2": "Snippet'leri anında herhangi bir metin alanına yapıştırın — <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span> tuşuna basın",
    "editorTitle": "✂️ MySnips — Düzenleyici",
    "importBtn": "⬆ İçe aktar", "exportBtn": "⬇ Dışa aktar",
    "shortcutLabel": "Klavye kısayolu:", "configureLink": "· Yapılandır",
    "tabTree": "Ağaç", "tabJson": "JSON",
    "hint": "Düzenlemek için bir isim veya değere çift tıklayın.",
    "treeMap": {"Company":"Şirket","VAT number":"Vergi no.","Company ID":"Şirket ID","Address":"Adres","Booking links":"Toplantı bağlantıları","Brand colors":"Marka renkleri","Primary (mauve)":"Birincil (mauve)","Secondary (blue)":"İkincil (mavi)","Emails":"E-postalar"},
    "col1b1": "Alt+S kısayolunu özelleştirin",
    "col1b2": "Klasörlerde düzenleyin",
    "col1b3": "Yerinde düzenleyin — çift tıklayın",
    "formTitle": "Tedarikçi kaydı",
    "labelCompany": "Şirket", "labelVat": "Vergi no.", "labelMsg": "Mesaj",
    "companyValue": "Acme Türkiye Ltd. Şti.",
    "textareaValue": "Merhaba,\nİsterseniz Zoom üzerinden de görüşebiliriz.\nİyi günler, Alex",
    "bubble1": KBD("açmak için"),
    "bubble2": "Göz atın, seçin, yapıştırın",
    "searchPlaceholder": "Ara…",
    "panelFolderCompany": "Şirket", "panelSnipVat": "Vergi no.", "panelSnipId": "Şirket ID",
    "panelSnipAddr": "Adres", "panelFolderBooking": "Toplantılar", "panelFolderColors": "Marka renkleri",
},
"et": {
    "step1": "Seadistage enimkasutatavad katkendid<br>otse laienduses",
    "step2": "Lisage katkendid kohe mis tahes tekstiväljale — vajutage <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Redaktor",
    "importBtn": "⬆ Impordi", "exportBtn": "⬇ Ekspordi",
    "shortcutLabel": "Kiirklahv:", "configureLink": "· Seadista",
    "tabTree": "Puu", "tabJson": "JSON",
    "hint": "Topeltklõps nimel või väärtusel muutmiseks.",
    "treeMap": {"Company":"Ettevõte","VAT number":"KMKR number","Company ID":"Reg. number","Address":"Aadress","Booking links":"Koosoleku lingid","Brand colors":"Brändi värvid","Primary (mauve)":"Esmane (mauve)","Secondary (blue)":"Teisene (sinine)","Emails":"E-mailid"},
    "col1b1": "Kohanda Alt+S otsetee",
    "col1b2": "Organiseeri kaustadesse",
    "col1b3": "Muuda kohapeal — topeltklõps",
    "formTitle": "Tarnija registreerimine",
    "labelCompany": "Ettevõte", "labelVat": "KMKR number", "labelMsg": "Sõnum",
    "companyValue": "Acme Eesti OÜ",
    "textareaValue": "Tere,\nSaame kohtuda ka Zoomi kaudu.\nParimate soovidega, Alex",
    "bubble1": KBD("avamiseks"),
    "bubble2": "Sirvi, vali, lisa",
    "searchPlaceholder": "Otsi…",
    "panelFolderCompany": "Ettevõte", "panelSnipVat": "KMKR nr.", "panelSnipId": "Reg. nr.",
    "panelSnipAddr": "Aadress", "panelFolderBooking": "Koosolekud", "panelFolderColors": "Brändi värvid",
},
"lt": {
    "step1": "Sukonfigūruokite dažniausiai naudojamus<br>fragmentus tiesiai plėtinyje",
    "step2": "Įterpkite fragmentus akimirksniu į bet kurį lauką — paspauskite <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Redaktorius",
    "importBtn": "⬆ Importuoti", "exportBtn": "⬇ Eksportuoti",
    "shortcutLabel": "Spartieji klavišai:", "configureLink": "· Konfigūruoti",
    "tabTree": "Medis", "tabJson": "JSON",
    "hint": "Dukart spustelėkite pavadinimą ar reikšmę redaguoti.",
    "treeMap": {"Company":"Įmonė","VAT number":"PVM kodas","Company ID":"Įmonės kodas","Address":"Adresas","Booking links":"Susitikimų nuorodos","Brand colors":"Prekės ženklo spalvos","Primary (mauve)":"Pirminė (mauve)","Secondary (blue)":"Antrinė (mėlyna)","Emails":"El. laiškai"},
    "col1b1": "Tinkinkite Alt+S klavišą",
    "col1b2": "Tvarkykite aplankuose",
    "col1b3": "Redaguokite vietoje — dukart spustelėkite",
    "formTitle": "Tiekėjo registracija",
    "labelCompany": "Įmonė", "labelVat": "PVM kodas", "labelMsg": "Žinutė",
    "companyValue": "Acme Lietuva UAB",
    "textareaValue": "Sveiki,\nGalime susitikti ir per Zoom.\nPagarbiai, Aleksas",
    "bubble1": KBD("atidaryti"),
    "bubble2": "Naršykite, pasirinkite, įterpkite",
    "searchPlaceholder": "Ieškoti…",
    "panelFolderCompany": "Įmonė", "panelSnipVat": "PVM kodas", "panelSnipId": "Įmonės kodas",
    "panelSnipAddr": "Adresas", "panelFolderBooking": "Susitikimai", "panelFolderColors": "Spalvos",
},
"lv": {
    "step1": "Konfigurējiet visbiežāk lietotos fragmentus<br>tieši pārlūkprogrammas paplašinājumā",
    "step2": "Uzreiz ievietojiet fragmentus jebkurā tekstlaukā — nospiediet <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Redaktors",
    "importBtn": "⬆ Importēt", "exportBtn": "⬇ Eksportēt",
    "shortcutLabel": "Tastatūras saīsne:", "configureLink": "· Konfigurēt",
    "tabTree": "Koks", "tabJson": "JSON",
    "hint": "Veiciet dubultklikšķi uz nosaukuma vai vērtības, lai rediģētu.",
    "treeMap": {"Company":"Uzņēmums","VAT number":"PVN reģ. nr.","Company ID":"Reģ. nr.","Address":"Adrese","Booking links":"Sanāksmju saites","Brand colors":"Zīmola krāsas","Primary (mauve)":"Primārā (mauve)","Secondary (blue)":"Sekundārā (zila)","Emails":"E-pasti"},
    "col1b1": "Pielāgojiet Alt+S saīsni",
    "col1b2": "Kārtojiet mapēs",
    "col1b3": "Rediģējiet — dubultklikšķis",
    "formTitle": "Piegādātāja reģistrācija",
    "labelCompany": "Uzņēmums", "labelVat": "PVN reģ. nr.", "labelMsg": "Ziņojums",
    "companyValue": "Acme Latvija SIA",
    "textareaValue": "Labdien,\nVar arī tikties Zoom platformā.\nAr cieņu, Alekss",
    "bubble1": KBD("atvēršanai"),
    "bubble2": "Pārlūkojiet, atlasiet, ievietojiet",
    "searchPlaceholder": "Meklēt…",
    "panelFolderCompany": "Uzņēmums", "panelSnipVat": "PVN nr.", "panelSnipId": "Reģ. nr.",
    "panelSnipAddr": "Adrese", "panelFolderBooking": "Sanāksmes", "panelFolderColors": "Krāsas",
},
"sl": {
    "step1": "Konfigurirajte najpogosteje uporabljene<br>odrezke neposredno v razširitvi",
    "step2": "Takoj vstavite odrezke v katerokoli polje — pritisnite <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Urejevalnik",
    "importBtn": "⬆ Uvozi", "exportBtn": "⬇ Izvozi",
    "shortcutLabel": "Bližnjica na tipkovnici:", "configureLink": "· Konfiguriraj",
    "tabTree": "Drevo", "tabJson": "JSON",
    "hint": "Dvojni klik na ime ali vrednost za urejanje.",
    "treeMap": {"Company":"Podjetje","VAT number":"Davčna številka","Company ID":"Matična številka","Address":"Naslov","Booking links":"Povezave za sestanke","Brand colors":"Barve blagovne znamke","Primary (mauve)":"Primarna (mauve)","Secondary (blue)":"Sekundarna (modra)","Emails":"E-pošta"},
    "col1b1": "Prilagodite bližnjico Alt+S",
    "col1b2": "Uredite v mapah",
    "col1b3": "Uredite neposredno — dvojni klik",
    "formTitle": "Registracija dobavitelja",
    "labelCompany": "Podjetje", "labelVat": "Davčna št.", "labelMsg": "Sporočilo",
    "companyValue": "Acme Slovenija d.o.o.",
    "textareaValue": "Spoštovani,\nLahko se srečamo tudi prek Zooma.\nLep pozdrav, Alex",
    "bubble1": KBD("za odpiranje"),
    "bubble2": "Prebrskajte, izberite, vstavite",
    "searchPlaceholder": "Iskanje…",
    "panelFolderCompany": "Podjetje", "panelSnipVat": "Davčna št.", "panelSnipId": "Matična št.",
    "panelSnipAddr": "Naslov", "panelFolderBooking": "Sestanki", "panelFolderColors": "Barve",
},
"mt": {
    "step1": "Ikkonfigura l-aktar snippets użati<br>direttament fl-estensjoni",
    "step2": "Daħħal snippets minnufih f'kull qasam tat-test — agħfas <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Editur",
    "importBtn": "⬆ Importa", "exportBtn": "⬇ Esporta",
    "shortcutLabel": "Shortcut tal-keyboard:", "configureLink": "· Ikkonfigura",
    "tabTree": "Siġra", "tabJson": "JSON",
    "hint": "Double-click fuq isem jew valur biex teditja.",
    "treeMap": {"Company":"Kumpanija","VAT number":"Numru tal-VAT","Company ID":"ID kumpanija","Address":"Indirizz","Booking links":"Links ta' laqgħat","Brand colors":"Kuluri tal-brand","Primary (mauve)":"Primarjo (mauve)","Secondary (blue)":"Sekondarju (blu)","Emails":"Emails"},
    "col1b1": "Ippersonalizza l-Alt+S",
    "col1b2": "Organizza fi folda",
    "col1b3": "Editja direttament — double-click",
    "formTitle": "Reġistrazzjoni tal-fornitur",
    "labelCompany": "Kumpanija", "labelVat": "Numru tal-VAT", "labelMsg": "Messaġġ",
    "companyValue": "Acme Malta Ltd.",
    "textareaValue": "Għandi pjaċir,\nNistgħu niltaqgħu wkoll fuq Zoom.\nSaħħa, Alex",
    "bubble1": KBD("biex tiftaħ"),
    "bubble2": "Fittex, agħżel, daħħal",
    "searchPlaceholder": "Fittex…",
    "panelFolderCompany": "Kumpanija", "panelSnipVat": "VAT nr.", "panelSnipId": "ID",
    "panelSnipAddr": "Indirizz", "panelFolderBooking": "Laqgħat", "panelFolderColors": "Kuluri",
},
"ga": {
    "step1": "Cumraigh na snippets is mó a úsáideann tú<br>go díreach sa bhreiseán",
    "step2": "Cuir isteach snippets láithreach in aon réimse téacs — brúigh <span style=\"background:rgba(255,255,255,0.25);border-radius:4px;padding:1px 7px;font-family:monospace;\">Alt+S</span>",
    "editorTitle": "✂️ MySnips — Eagarthóir",
    "importBtn": "⬆ Iompórtáil", "exportBtn": "⬇ Easpórtáil",
    "shortcutLabel": "Aicearra méarchláir:", "configureLink": "· Cumraigh",
    "tabTree": "Crann", "tabJson": "JSON",
    "hint": "Cliceáil faoi dhó ar ainm nó luach chun eagarthóireacht a dhéanamh.",
    "treeMap": {"Company":"Cuideachta","VAT number":"Uimhir CBL","Company ID":"Uimhir chláraithe","Address":"Seoladh","Booking links":"Naisc cruinnithe","Brand colors":"Dathanna branda","Primary (mauve)":"Príomhúil (mauve)","Secondary (blue)":"Tánaisteach (gorm)","Emails":"Ríomhphoist"},
    "col1b1": "Saincheap aicearra Alt+S",
    "col1b2": "Eagraigh i bhfillteáin",
    "col1b3": "Cuir in eagar — cliceáil faoi dhó",
    "formTitle": "Clárú soláthraí",
    "labelCompany": "Cuideachta", "labelVat": "Uimhir CBL", "labelMsg": "Teachtaireacht",
    "companyValue": "Acme Éireann Teo.",
    "textareaValue": "A chara,\nIs féidir linn bualadh le chéile ar Zoom freisin.\nLe meas, Alex",
    "bubble1": KBD("chun oscailte"),
    "bubble2": "Brabhsáil, roghnaigh, cuir isteach",
    "searchPlaceholder": "Cuardaigh…",
    "panelFolderCompany": "Cuideachta", "panelSnipVat": "Uimhir CBL", "panelSnipId": "Uimhir chlár.",
    "panelSnipAddr": "Seoladh", "panelFolderBooking": "Cruinnithe", "panelFolderColors": "Dathanna",
},
}

# ── JS inject ─────────────────────────────────────────────────────────────────
INJECT_JS = """(data) => {
    const el=(id)=>document.getElementById(id);
    const set=(id,h)=>{const e=el(id);if(e)e.innerHTML=h;};
    const txt=(id,t)=>{const e=el(id);if(e)e.textContent=t;};
    set('step1-text',data.step1); set('step2-text',data.step2);
    txt('editor-title',data.editorTitle); txt('import-btn',data.importBtn);
    txt('export-btn',data.exportBtn); txt('shortcut-label',data.shortcutLabel);
    txt('configure-link',data.configureLink); txt('tab-tree',data.tabTree);
    txt('tab-json',data.tabJson); txt('hint-text',data.hint);
    document.querySelectorAll('.options-card .item-name').forEach(n=>{
        const t=n.textContent.trim(); if(data.treeMap[t]) n.textContent=data.treeMap[t];
    });
    txt('col1-bubble1-text',data.col1b1); txt('col1-bubble2-text',data.col1b2);
    txt('col1-bubble3-text',data.col1b3);
    txt('form-title',data.formTitle); txt('label-company',data.labelCompany);
    txt('label-vat',data.labelVat); txt('label-msg',data.labelMsg);
    el('input-company').value=data.companyValue;
    el('textarea-msg').value=data.textareaValue;
    set('bubble1',data.bubble1); txt('bubble2',data.bubble2);
    el('panel-search-input').placeholder=data.searchPlaceholder;
    txt('folder-company',data.panelFolderCompany); txt('snippet-vat',data.panelSnipVat);
    txt('snippet-id',data.panelSnipId); txt('snippet-addr',data.panelSnipAddr);
    txt('folder-booking',data.panelFolderBooking); txt('folder-colors',data.panelFolderColors);
}"""

MEASURE_JS = """() => ['col1-bubble1','col1-bubble2','col1-bubble3','callout1','callout2'].map(id=>{
    const e=document.getElementById(id); return {id,h:e?Math.round(e.clientHeight):0,sh:e?Math.round(e.scrollHeight):0};
})"""

# EN reference heights
EN_HEIGHTS = {}

async def main():
    global EN_HEIGHTS
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        url = HTML.resolve().as_uri()

        # Measure EN reference
        page = await browser.new_page(viewport={"width":1280,"height":800})
        await page.goto(url, wait_until="networkidle")
        en_measures = await page.evaluate(MEASURE_JS)
        await page.close()
        EN_HEIGHTS = {m['id']: m['h'] for m in en_measures}
        print(f"EN reference heights: {EN_HEIGHTS}")

        overflows = {}
        ok_count = 0

        for lang, data in LANGS.items():
            page = await browser.new_page(viewport={"width":1280,"height":800})
            await page.goto(url, wait_until="networkidle")
            await page.evaluate(INJECT_JS, data)

            measures = await page.evaluate(MEASURE_JS)
            out_path = OUT / f"screenshot-store-{lang}.png"
            await page.screenshot(path=str(out_path))
            await page.close()

            lang_overflows = []
            for m in measures:
                en_h = EN_HEIGHTS.get(m['id'], 0)
                if m['h'] > en_h + 2:
                    lang_overflows.append(f"{m['id']}(+{m['h']-en_h}px)")

            if lang_overflows:
                overflows[lang] = lang_overflows
                print(f"  [{lang}] ⚠  overflow: {', '.join(lang_overflows)}")
            else:
                ok_count += 1
                print(f"  [{lang}] ✓  {out_path.name}")

        await browser.close()

    print(f"\n✓ {ok_count}/{len(LANGS)} languages OK")
    if overflows:
        print(f"⚠  {len(overflows)} languages with overflows:")
        for lang, ov in overflows.items():
            print(f"   {lang}: {ov}")

if __name__ == "__main__":
    asyncio.run(main())
